# Generated by Django 5.0 on 2024-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
                ('number', models.IntegerField(default='0')),
                ('querry', models.CharField(default='', max_length=1000)),
                ('add1', models.CharField(default='', max_length=60)),
                ('add2', models.CharField(default='', max_length=60)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zip', models.IntegerField(default='0')),
            ],
        ),
    ]
