# Generated by Django 5.0 on 2024-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseimg', models.ImageField(upload_to='')),
                ('coursename', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
