# Generated by Django 5.0 on 2024-02-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseduration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='shortdescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='subheading',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseId',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseimg',
            field=models.ImageField(upload_to='courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='coursename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
