# Generated by Django 5.0 on 2024-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0003_courses_courseduration_courses_shortdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='coursename',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='courses',
            name='shortdescription',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subheading',
            field=models.CharField(default='', max_length=20),
        ),
    ]
