# Generated by Django 5.0 on 2024-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0005_courses_category_courses_discounted_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
