# Generated by Django 5.0.2 on 2024-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
