# Generated by Django 5.0.2 on 2024-04-21 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbils', '0007_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
